### ISSUE TITLE
Letter size generation generates doubled QR code

### ISSUE THREAD

**Issue by duckpuppy** [FranciscodeMaussion/RocketBookPages#14]
**Describe the bug**
When generating letter size templates, the QR code at the bottom is doubled, with one QR code generated slightly offset from the other.

**To Reproduce**
`rocketqr create -f Letter -t 0 -q 1 -n True`

**Expected behavior**
The generated page should have a single QR code in the appropriate place

**Screenshots**
![Screen Shot 2020-06-08 at 11 58 31 AM](https://user-images.githubusercontent.com/19253/84053135-807f7980-a97f-11ea-8b6b-a791f7606ed9.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Python: 3.7.7

**Comment by FranciscodeMaussion** [comment]
sorry for the issue, play a little bit with the qr position parameters and it will work.
Please let me know if you reach a good qr position and wich is to correct the default json file
