### ISSUE TITLE
Custom page (RocketBook mini)

### ISSUE THREAD

**Issue by mimmori** [FranciscodeMaussion/RocketBookPages#3]
With the reference of the issue #2, it would be interesting to try to generate the icons at the bottom of the page to see if they work. In case of working add the option in the generation phase.

**Comment by FranciscodeMaussion** [comment]
you mean custom icons?

**Comment by mimmori** [comment]
No, i mean the standard set of icon present on the bigger models.

**Comment by FranciscodeMaussion** [comment]
[Rocketbook-Mini-Base.pdf](https://github.com/FranciscodeMaussion/RocketBookPages/files/2837659/Rocketbook-Mini-Base.pdf)

**Comment by mimmori** [comment]
Super fast! I Will try It. Does It work?

**Comment by FranciscodeMaussion** [comment]
It should, is only an sketch and I have to change some parts in the project, but it should work good
Please let me know if it worked. Maybe another day I make the changes and push them

**Comment by mimmori** [comment]
I tried to scan some qr code found on the web and the text Is P01 V0V S0000000 for the mini format. but in your sketch the text Is P01 V0R S0000000.

**Comment by FranciscodeMaussion** [comment]
That is because each type of page has a different code (I think line
versión has V0V)

**Comment by mimmori** [comment]
I assume your sketch need to Be update then...
