### ISSUE TITLE
Dotgrid not working for me

### ISSUE THREAD

**Issue by kb1ooo** [FranciscodeMaussion/RocketBookPages#8]
Running `rocketqr create -q 1 -f Letter -t 0` is supposed to produce dotgrid pages.  However, it does not and produces the same output as `rocketqr create -q 1 -f Letter -t 1`.

**Comment by FranciscodeMaussion** [comment]
This is a known issue, the solution is in process. If you would like to help it would be great for me.
A quick fix is to change the base file for that size.

**Comment by kb1ooo** [comment]
> This is a known issue, the solution is in process. If you would like to help it would be great for me.
> A quick fix is to change the base file for that size.

What are you trying to do instead?

**Comment by FranciscodeMaussion** [comment]
Draw lines from the base files

**Comment by kb1ooo** [comment]
Ok, what's the disadvantage using the template?  That it makes it hard to arbitrarily resize to other paper dimensions?

**Comment by FranciscodeMaussion** [comment]
Yes, but the worst part is that it is difficult for a user to add a template.
And I would like to make more lightweight the program.

**Comment by FranciscodeMaussion** [comment]
this is next in queue, whenever someone want to help, it is welcome

**Comment by sparky1088** [comment]
I pulled tried this week to generate and noticed this is still a problem. im not much of a programmer myself but im willing to test if someone needs it.

Edit: i did notice that the lined was also not adding lines when I tested it so it might have something to do with when adding anything to the pages.

**Comment by FranciscodeMaussion** [comment]
yes, I will make a tag with the one working since I am not having much time to work in this RN

**Comment by FranciscodeMaussion** [comment]
Well I have modified the program to use custom templates, it will not produce the dotgrid by default but you can download an create a template with the template creator. if you @sparky1088 can try it, it would be great.
